name: appwrite_function
description: Appwrite Function for Firebase Cloud Messaging notifications
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^3.0.0
